services:
  nuxt:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./app:/app
    command: npm run dev
    ports:
      - "3000:3000"
    tty: true
  function:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./function:/app
    tty: true
    ports:
      - "5001:5001"
      - "4000:4000"
#     networks:
#       - cinnamon-network

# networks:
#   cinnamon-network:
#     name: cinnamon-network